version : '3'

services:
  user-service:
    build: ./User
    volumes:
      - ./User:/usr/src/app 
    ports: 
      - 5001:3000 
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'


 