version : '3'

services:
  user-service:
    build: ./User
    volumes:
      - ./User:/usr/src/app 
    ports: 
      - 5001:4000 
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  admin-service:
    container_name: admin
    image: fleetmart_user-service
    volumes:
      - ./Admin:/usr/src/app
    ports:
      - 5000:4000
  department-service:
    container_name: department
    image: fleetmart_user-service
    volumes:
      - ./Department:/usr/src/app
    ports:
      - 4000:4000
  product-service:
    container_name: product
    image: fleetmart_user-service
    volumes:
      - ./Product:/usr/src/app
    ports:
      - 2000:4000



 